### ISSUE TITLE
✨ Add time ago (next)

### ISSUE THREAD

**Issue by aguilaair** [papercups-io/papercups_flutter#14]
![imagen](https://user-images.githubusercontent.com/29983481/101284808-2c483b80-37e2-11eb-8b85-4f67e945fd24.png)

 Will be using https://pub.dev/packages/timeago asi it support many locales

**Comment by Fiyiin** [comment]
I'm picking it up

**Comment by aguilaair** [comment]
That's great @Fiyiin, thanks!
