### ISSUE TITLE
Add support for push notification

### ISSUE THREAD

**Issue by ariaseta** [papercups-io/papercups_flutter#54]
I have found quite interesting feature from https://docs.kommunicate.io/docs/flutter-pushnotification

Do you have plan to integrate the same feature?

**Comment by aguilaair** [comment]
Hey, definitely on the roadmap! We'd probably have to do some work on the papercups backend to make it work, but it is something that we do want to do (cc @reichert621 & @cheeseblubber )

If you want to help out that is always welcome too!

**Comment by themisir** [comment]
> Hey, definitely on the roadmap! We'd probably have to do some work on the papercups backend to make it work, but it is something that we do want to do (cc @reichert621 & @cheeseblubber )
> 
> If you want to help out that is always welcome too!

PS: For bare minimum if you could integrate Firebase Cloud Messaging with your backend it could be easily used for both ios and android platforms and you could expose an api function on client SDK to attach FCM device tokens to chat users.

**Comment by aguilaair** [comment]
As Papercups is in Maintainance mode, this feature is unlikely to be implementable. Closing issue.
