### ISSUE TITLE
Image/attachment upload 

### ISSUE THREAD

**Issue by aguilaair** [papercups-io/papercups_flutter#58]
Still WIP in the Papercups backend, therefore blocked

**Comment by aguilaair** [comment]
You can now manage attachments on papercups, will try to take a loos soon(ish)
@Fiyiin do you want to take a look?

**Comment by ryg-git** [comment]
if it is ok can I take up this issue?

**Comment by aguilaair** [comment]
Of course!

**Comment by aguilaair** [comment]
Hey @ryg-git! How is this coming along? Need any help?

**Comment by aguilaair** [comment]
Thanks @ryg-git, I'll take a look this weekend!

I think option 1 is the cleanest regarding how to handle the download. However, we could have option 1 as the default behaviour and let the user override the result by adding the `onMessageBubbleTap ` function.

What do you think?

**Comment by ryg-git** [comment]
Yes I also think so, giving a default behaviour and let the user change it if they want different behaviour by overriding the function seems like a good idea to me too

**Comment by aguilaair** [comment]
This will be included in the next release!
