### ISSUE TITLE
"Reply to" feature (should this be implemented?)

### ISSUE THREAD

**Issue by aguilaair** [papercups-io/papercups_flutter#59]
Replying to certain conversations by sliding like in Telegram/Whatsapp? we could just use the quote block feature from markdown for this.

@cheeseblubber / @reichert621

**Comment by aguilaair** [comment]
Closing this as @reichert621 and @cheeseblubber haven't commented on this + we are using the quotes to stylize the attachments

**Comment by reichert621** [comment]
hey @aguilaair sorry we missed this! i think this could be an interesting feature at some point, but not a priority at the moment 👍
