### ISSUE TITLE
Chats are not persisted

### ISSUE THREAD

**Issue by steebchen** [papercups-io/papercups_flutter#69]
When I render the widget, write a message, then close and re-open, all messages are gone. It seems that the messages re-appear once the chat text input is focused. Also, another thing which is a bit weird: once re-opened, it seems that a new conversation is created instead of using the old one. It seems to be easily reproducible. I'm using 2.1.0+1.

My code:

```dart
PaperCupsWidget(
  closeAction: () {
    Navigator.of(context, rootNavigator: true).pop();
  },
  props: Props(
    accountId: "...",
    customer: CustomerMetadata(
      externalId: res.viewer.id,
      email: res.viewer.email,
      name: res.viewer.name,
    ),
  ),
);
```

It seems #68 is related

**Comment by aguilaair** [comment]
I'll investigate this ASAP

**Comment by aguilaair** [comment]
@steebchen please check if 2.1.1 fixes the issue

**Comment by steebchen** [comment]
It does. Thanks! It could load a bit faster (or also be cached), but the main issue is indeed fixed.
