### ISSUE TITLE
CustomerMetadata doesn't set the otherMetadata

### ISSUE THREAD

**Issue by CharlesMangwa** [papercups-io/papercups_flutter#76]
First things first, thanks for this library: it works wonders! 🎉

I'm just facing an issue right now that could be coming either from this package or Papercups API itself, maybe you could shed some lights on what's going on. Long story short: I cannot set customers metadata.

If I provide the following to the widget:

```dart
customer: CustomerMetadata(
  name: 'userName',
  externalId: 'userId',
  otherMetadata: {
    'random_field': 'random field value',
  },
),
````

Both `name` and `externalId` are saved and shown in the Papercups dashboard but the content of `otherMetadata` is not and `metadata` is still `null`.

---

I dug a little bit in the source code and things seems to be happening over here:

https://github.com/papercups-io/papercups_flutter/blob/1360acf5bfa4bfb589db1615d915532ead9458d2/lib/utils/apiInteraction/updateUserMetadata.dart#L22-L29

If I use `https://app.papercups.io/api/v1/customers` as done in the [API endpoint docs](https://docs.papercups.io/api-endpoints#update-a-customer) (instead of the `https://app.papercups.io/api/customers` used by the package here), then `https://app.papercups.io/api/v1/customers/[id]/metadata` returns a `404` with `{"errors":{"detail":"Bad Request"}}%`. Maybe there was a change over there?

FWIW I also created an issue in the the main repo https://github.com/papercups-io/papercups/issues/995 as when I try to perform the same action via the call mentioned in the API endpoint docs, I get the same result: `metadata` is `null`.

**Comment by aguilaair** [comment]
Hey! Thanks for the issue, sorry for not getting back to you before, I missed it :)

I'll investigate this a bit and see what the solution could be.

**Comment by aguilaair** [comment]
Movin this to blocked as it seems to be an API issue

**Comment by reichert621** [comment]
@CharlesMangwa can you try this instead and see if it works?

```dart
customer: CustomerMetadata(
  name: 'userName',
  externalId: 'userId',
  otherMetadata: {
    metadata: {random_field: 'random field value'}
  },
),
```

@aguilaair I think the issue is that `otherMetadata` just gets spread across the the updates (here's what the type should look like https://github.com/papercups-io/chat-window/blob/master/helpers/types.ts#L1-L14), so devs might assume that `otherMetadata` can include whatever ad hoc metadata they want, when in fact they would need to put that in a nested `otherMetadata.metadata` object

It's probably my fault for naming it `CustomerMetadata` in the first place, and then adding a field for `metadata` 😅

**Comment by aguilaair** [comment]
Ohhhhhhhhhhhh that makes sense lol. @CharlesMangwa lmk if this fixes the issue

**Comment by CharlesMangwa** [comment]
Hi both, gave it a quick try today but to no avail (`metadata` is still returned as `null`). I'd suspect this could be because https://github.com/papercups-io/papercups/issues/995 is still pending?

Btw: we might need to update the following
https://github.com/papercups-io/papercups_flutter/blob/ebc5162948ec4635d298c17291cf061ad3be1d2f/lib/models/classes.dart#L19

to accept `Map<String, dynamic>?` or an exhaustive type instead.
